# Generated by Django 5.2.6 on 2025-09-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('candidate', 'exam')},
        ),
    ]
