# Generated by Django 5.2.6 on 2025-09-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_manager',
            field=models.CharField(choices=[('Gulnoza', 'Gulnoza'), ('Iroda', 'Iroda'), ('Abdurahmon', 'Abdurahmon'), ('Boshqa', 'Boshqa')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='region',
            field=models.CharField(default='Abdurahmon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_position',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
