# Generated by Django 5.2.6 on 2025-11-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_candidate_email_remove_candidate_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Javob', 'verbose_name_plural': 'Javoblar'},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Urinish', 'verbose_name_plural': 'Urinishlar'},
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Nomzod', 'verbose_name_plural': 'Nomzodlar'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Javob varianti', 'verbose_name_plural': 'Javob variantlari'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Imtihon', 'verbose_name_plural': 'Imtihonlar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Javob vaqti'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.attempt', verbose_name='Urinish'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.choice', verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='To‘g‘rimi?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='Matnli javob'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.candidate', verbose_name='Nomzod'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.exam', verbose_name='Imtihon'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='focus_violations',
            field=models.PositiveIntegerField(default=0, verbose_name='Fokus buzilishlari'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Savollar tartibi'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugatgan vaqt'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Savollar soni'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='Brauzer ma’lumoti'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ro‘yxatdan o‘tgan vaqt'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_manager',
            field=models.CharField(choices=[('Gulnoza', 'Gulnoza'), ('Iroda', 'Iroda'), ('Abdurahmon', 'Abdurahmon'), ('Boshqa', 'Boshqa')], max_length=50, verbose_name='HR menejer'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Hudud'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_position',
            field=models.CharField(max_length=100, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='To‘g‘ri javobmi?'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exam.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Variant matni'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Davomiyligi (daqiqada)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_focus_violations',
            field=models.PositiveIntegerField(default=0, verbose_name='Maks. fokus buzilishlar soni'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='shuffle_questions',
            field=models.BooleanField(default=True, verbose_name='Savollarni aralashtirish'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Imtihon nomi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam', verbose_name='Imtihon'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'Variantli'), ('TF', 'To‘g‘ri/Yolg‘on'), ('SHORT', 'Qisqa javob')], default='MCQ', max_length=10, verbose_name='Savol turi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Savol matni'),
        ),
    ]
