# Generated by Django 5.2.6 on 2025-12-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
