# Generated by Django 5.2.6 on 2025-12-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_jobapplication_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
